### ISSUE TITLE
Implement a search bar

### ISSUE THREAD

**Issue by AnthonyMed13** [uprm-inso4115-2023-2024-s2/semester-project-photofit-a-closet-inventory-app#10]
For this task we would need to make a search bar to navigate the clothes and outfits stored in the local storage. 

We could add filters based on different things like seasons and the colors of the outfit. This could be its own issue

Tentative Points:

Urgency: 7
Difficulty: --

**Comment by RicardoJRSs** [comment]
I would like to work on this task

**Comment by AngelGonzs** [comment]
If possible, I could assist on this task as well.
