### ISSUE TITLE
Wire up Filter UI

### ISSUE THREAD

**Issue by diego-velez-upr** [uprm-inso4115-2023-2024-s2/semester-project-photofit-a-closet-inventory-app#101]
In issue #61, the `Filter` component was created but not wired up, that is to say that it does not work. The issue is supposed to fix that, it'll allow users to filter out their clothes.

**Comment by Adhel-Esteban1** [comment]
I want to follow up on this issue, here are the things I believe could be specific to finish this, feel free to correct me where needed:
- a rectangular module with a search bar at the top and three drop-down selection menus for filtering clothing items based on color, type (shirt, pants, shoes), and sleeve size (no sleeve, small sleeve, large sleeve). 
- Also, the three sections should be drop downs, and this should be a modular file, such that it can be easily used in different areas. 

Recommended points:
Urgency - 4
Dificulty - 6
