### ISSUE TITLE
[Lecture Topic Task] Implement at least  4 of the different diagram types

### ISSUE THREAD

**Issue by AnthonyMed13** [uprm-inso4115-2023-2024-s2/semester-project-photofit-a-closet-inventory-app#103]
• The team uses various diagram types to complement their project
    documentation. They use at least 4 of the diagram types below in a
    way that ENHANCES their documentation.

    – System scope: context, problem, frame diagrams Conceptual
    – structures: entity-relationship diagrams Activities and data: SADT
    – diagrams Information flows: dataflow diagrams System operations:
    – use case diagrams Interaction scenarios: event trace diagrams
    – System behaviors: state machine diagrams

Tentative Points:
Urgency: 8
Difficulty: 8

**Comment by Adhel-Esteban1** [comment]
Make sure to specify if this is a lecture topic task.

**Comment by AnthonyMed13** [comment]
Finished adding these to the documentation
