### ISSUE TITLE
[Lecture Topic Task] Discussion of Satisfiability and Feasibility in Domain Requirements

### ISSUE THREAD

**Issue by AnthonyMed13** [uprm-inso4115-2023-2024-s2/semester-project-photofit-a-closet-inventory-app#104]
The team added to their analytical part a section documenting a requirements and domain model inspection. They use at least a defect-driven checklist and a quality-driven checklist. Their report includes who the inspectors are, the (substantial) question catalog the inspectors used, the items considered, the finding of the inspectors.

Tentative Points:
Urgency: 4
Difficulty: 7

**Comment by Jandel7** [comment]
Me gustaria dividir este task en dos, esta bien ?

**Comment by Adhel-Esteban1** [comment]
The title needs some updating

**Comment by print-Eruki** [comment]
This was review by @HectorSotelo and me, and gave permission to the dev to closed this issue as done/completed.
