### ISSUE TITLE
[Milestone 2 Feedback Fix] Highlighted Changes

### ISSUE THREAD

**Issue by AnthonyMed13** [uprm-inso4115-2023-2024-s2/semester-project-photofit-a-closet-inventory-app#110]
Professor's Comment: Changes are not highlighted.

Google Doc has a "View History" feature we can backtrack our document versions and see the unhighlighted changes.

Also our standard for changes is:
-New additions Yellow
-Deleted Red WITH Strikethrough

**Comment by HectorSotelo** [comment]
Professor's Comment: Changes are not highlighted.

Google Doc has a "View History" feature we can backtrack our document versions and see the unhighlighted changes.

Also our standard for changes is: 
-New additions Yellow
-Deleted Red WITH Strikethrough

**Comment by Cristina-Figueroa** [comment]
Added the deleted parts (strikethrough and red font) and highlighted (in yellow) everything that was changed during Milestone #2

**Comment by Cristina-Figueroa** [comment]
I reviewed the document until now and all highlights have been added. Again, Milestone #2 changes are in Yellow, Deletion are red font and strikethrough, and finally for changes for Milestone #3 they are highlighted in green. I will close the issue now.
