### ISSUE TITLE
[Lecture Topic Task] Add Domain Facets to Documentation

### ISSUE THREAD

**Issue by AnthonyMed13** [uprm-inso4115-2023-2024-s2/semester-project-photofit-a-closet-inventory-app#116]
Add Domain Facet to documentation so it can be analyzed from various aspects. 

Urgency: 7
Difficulty: 3

**Comment by Adhel-Esteban1** [comment]
To make sure you get these points on time, I will close this issue now, knowing that you will finish this on time.
