### ISSUE TITLE
Implement "Make Your Outfit" UI. 

### ISSUE THREAD

**Issue by Adhel-Esteban1** [uprm-inso4115-2023-2024-s2/semester-project-photofit-a-closet-inventory-app#119]
Task Description:
Develop the user interface (UI) from Figma for the PhotoFit application, specifically designed for manually creating outfits using the clothes stored in the database. The Add Outfits UI must provide users with an intuitive and efficient platform to mix and match clothing items, allowing them to experiment with different combinations and save their preferred outfits for future reference. There is a Figma file for this. 

Recommended points:
Urgency - 7
Dificulty - 7

**Comment by Adhel-Esteban1** [comment]
If multiple developers take this task, the difficulty and urgency points can be increased to help the developers working on it.

**Comment by Cristina-Figueroa** [comment]
Add Outfits page -> Make Your Outfit page in Figma

![image](https://github.com/uprm-inso4115-2023-2024-s2/semester-project-photofit-a-closet-inventory-app/assets/70239790/50894799-5aac-4457-8b54-c35dcea89b7f)

**Comment by Cristina-Figueroa** [comment]
Notes:

Physical Components:
- add a filters search bar: includes three dropdown: Color, Type, Sleeve Size, etc
- preview photos of database
- checkmark or highlight photo to show it was selected for the outfit

Functionality:
  - make filters search bar work
  - select clothe feature to add to database (that combination of clothing)
  - add box with new outfit into the top of Outfits page feed (latest to oldest)
