### ISSUE TITLE
Implemented New Outfits UI

### ISSUE THREAD

**Issue by Adhel-Esteban1** [uprm-inso4115-2023-2024-s2/semester-project-photofit-a-closet-inventory-app#128]
Task Description: This task will come after issue #126, as it will focus on implementing the new UI, and refining the existing one to have the working buttons, and scrolling features for ease of navigation

Recommended points:
Urgency - 7
Dificulty - 9

**Comment by Cristina-Figueroa** [comment]
New Outfits UI from Figma

![image](https://github.com/uprm-inso4115-2023-2024-s2/semester-project-photofit-a-closet-inventory-app/assets/70239790/bb98b3cd-eafa-4862-9504-e57b30a2f303)

**Comment by HectorSotelo** [comment]
I think it would make the Outfits UI look cleaner and more understandable if the "Edit" button was on the top left if we wanted to rename or delete an outfit and to edit the components OF the outfit there would be an "Edit" button once you click and access an Outfit

**Comment by Adhel-Esteban1** [comment]
> I think it would make the Outfits UI look cleaner and more understandable if the "Edit" button was on the top left if we wanted to rename or delete an outfit and to edit the components OF the outfit there would be an "Edit" button once you click and access an Outfit

I coded on this area and I believe that would make it a bit more complicated. However, we will remain open to this option should the need arise. It would look cleaner, yes, but I think that if you want to edit a outfit item it would be easier to just click edit on the item itself rather than click edit, and then click the item you want to edit. That's two taps. Edit on the widget is just one tap. 

However, we can use the above edit page to delete items.

**Comment by Adhel-Esteban1** [comment]
Also I want to assign myself as part of this work as I had to implement a bit part of this on issue #120. I made some contributions here:

- Implemented physical component that can be reused
- Scrollable feature
- Edit button mockups (don't do any action for the moment)
- Image placeholders
- Styled the entire thing (at least on iOS). I will soon test it on Android and see what is needed.

**Comment by Cristina-Figueroa** [comment]
New Outfits UI was implemented and merged to main branch in GitHub. Issue can be closed now.
