### ISSUE TITLE
Filtering in wardrobe collection

### ISSUE THREAD

**Issue by RicardoJRSs** [uprm-inso4115-2023-2024-s2/semester-project-photofit-a-closet-inventory-app#13]
Implement better filtering for the storage so the user can mark their outfits by favorites, color or occasion for better visualization of the closet.

**Comment by diego-velez-upr** [comment]
Branch `saving-filtering-wardrobe` was created for this change, as well as PR #59.

Most of the work was done in task #9, nevertheless, this allows for filtering clothes based on clothe criteria.

**Comment by HectorSotelo** [comment]
All good!
