### ISSUE TITLE
[Lecture Topic Task] Events, actions and behaviors feedback 

### ISSUE THREAD

**Issue by JadiellMV** [uprm-inso4115-2023-2024-s2/semester-project-photofit-a-closet-inventory-app#134]
Task Description: Address feedback on "events, actions and behaviors" : Most of the items under "events, actions, and behaviors" are not labeled as to which of the three they are. The function signatures are still separate from the actions. sortCloset still only takes a category: where do the Clothes come from?

Recommended points:
Urgency - 5
Dificulty - 3

**Comment by HectorSotelo** [comment]
@JadiellMV Moving you to issue #114 , as it was created for issues like this. Will delete by tomorrow, just letting you know.
