### ISSUE TITLE
[Lecture Topic Task] Demonstrate Application of Risk Reduction Tactics in Project

### ISSUE THREAD

**Issue by JoseLQV** [uprm-inso4115-2023-2024-s2/semester-project-photofit-a-closet-inventory-app#138]
Briefly describe the project where risk reduction tactics are being applied. Include information about the project's purpose, scope, and key objectives.

Risk Reduction Tactics:
Detail the specific risk reduction tactics or strategies that are implemented or planned for this project. This may include methodologies, tools, processes, or best practices used to identify, assess, mitigate, and monitor risks.

Benefits and Impact:
Explain the benefits and impact of implementing these risk reduction tactics. How do they contribute to the project's success, efficiency, and resilience against potential risks?

Expected Deliverables:
Outline the expected deliverables or outcomes that demonstrate the application of risk reduction tactics. This could be in the form of reports, analyses, documentation, or tangible project milestones.

**Comment by print-Eruki** [comment]
Will this task be more focused on risks regarding the satisfaction/completion of the project's requirements?
