### ISSUE TITLE
Set up code base for the React framework

### ISSUE THREAD

**Issue by Adhel-Esteban1** [uprm-inso4115-2023-2024-s2/semester-project-photofit-a-closet-inventory-app#14]
In this task, your primary objective is to establish the foundational structure of the StudyPet project using the React framework. Create a basic skeleton that lays the groundwork for future development. Set up essential files and directories, including the main application file, components, styles, and any necessary configuration files. Ensure that the project can be successfully initiated, even if it displays a basic white screen on the phone. This initial setup provides a solid foundation for other developers to build upon, streamlining the collaborative development process and allowing for seamless integration of features and functionalities as the project progresses.

Urgency 5
Difficulty 2

**Comment by print-Eruki** [comment]
I believe the points distributions is skewered, what do you think about 

Urgency 5
Difficulty 2

This is a more realistic pts distributions in my opinion

**Comment by Adhel-Esteban1** [comment]
Unsure, I'd argue that urgency at least goes high. But for the amount of work required I would say urgency 10 and difficulty 3 or 4 would be nice. I'm very generous with that, and I wouldn't want whoever does this to have to do a bunch of other things. 

Whoever does this must set up a working skeleton that displays on the phone. That in itself is a lot of work. A blank screen, a code base, and upload it to Git Hub. Big work, big responsibility.

**Comment by sandy-marrero** [comment]
Task has been completed, adding to the README all the necessary steps to run and using a template that will facilitate the addition of the different features that will be shown in milestone 1.
