### ISSUE TITLE
[Lecture Topic Task] Analyze Requirements Inconsistencies for Specific Types of Clashes

### ISSUE THREAD

**Issue by JoseLQV** [uprm-inso4115-2023-2024-s2/semester-project-photofit-a-closet-inventory-app#141]
Task Description:

Project Overview:
Briefly describe the project where requirements inconsistencies are being analyzed for specific types of clashes. Include information about the project's purpose, scope, and key objectives related to requirements analysis.

Types of Clashes:
Identify and categorize the specific types of clashes or inconsistencies in requirements that are being analyzed in the project. Describe each type of clash and its impact on project planning and implementation.

Analysis Approach:
Explain the approach or methodology used in the project to analyze requirements inconsistencies. Discuss the tools, techniques, and criteria used to identify, prioritize, and resolve clashes effectively.

Impact Assessment:
Describe the process of assessing the impact of requirements inconsistencies on project deliverables, timeline, and stakeholder satisfaction. Discuss how the analysis results are used to make informed decisions and mitigate risks.

Expected Deliverables:
Outline the expected deliverables or outcomes related to the analysis of requirements inconsistencies. This could include inconsistency reports, mitigation strategies, stakeholder communication plans, or other relevant documentation.

Recommended points:
Urgency - # 4
Dificulty - # 4

**Comment by print-Eruki** [comment]
Mark this as a LTT? Is this going to be reported/added into the documentation?

**Comment by AnthonyMed13** [comment]
Closing this inorder for you to get the points
