### ISSUE TITLE
[Lecture Topic Task] System Scope

### ISSUE THREAD

**Issue by HectorSotelo** [uprm-inso4115-2023-2024-s2/semester-project-photofit-a-closet-inventory-app#149]
Task Description:
Diagram giving context, explaining problems or concepts

Recommended points:
Urgency - 2
Dificulty - 5

**Comment by AnthonyMed13** [comment]
Added this to the documentation

**Comment by AnthonyMed13** [comment]
![WhatsApp Image 2024-04-26 at 16 59 24_5e5948bd](https://github.com/uprm-inso4115-2023-2024-s2/semester-project-photofit-a-closet-inventory-app/assets/94082488/36e44e89-d138-4f1e-86e8-212264539317)


This diagram adds the context for the interactions between the User and the Closet. It shows how the user needs to define certain parameters to add new clothes and how the closet fetches the required clothes from the database. This diagram is for an easier understanding of the closet functionality
