### ISSUE TITLE
[Lecture Topic Task] Conceptual Structures

### ISSUE THREAD

**Issue by HectorSotelo** [uprm-inso4115-2023-2024-s2/semester-project-photofit-a-closet-inventory-app#150]
Task Description:
Entity-Relationship diagram

Recommended points:
Urgency - 2
Dificulty - 5

**Comment by warm007** [comment]
![Image](https://github.com/uprm-inso4115-2023-2024-s2/semester-project-photofit-a-closet-inventory-app/assets/112134756/5a21b8cc-4ce4-4fed-ab37-70e3d0252ea6)

**Comment by AnthonyMed13** [comment]
Brief description of the diagram:

The entity diagram illustrates two main entities: Clothing and Equipment.
The Clothe entity has attributes including _name, _link, _type, _color, and _sleeveSize, which detail the specific characteristics of each garment. For example, "_name" represents the name of the item, _link probably points to an image or product page, "_type" specifies the category (such as shirt, pants, shoes or unknown), "_color" indicates the color of the clothing ( among them are black, white, gray, navy, blue, green, red, yellow, orange, pink, purple, brown or unknown) and "_sleeveSize" quantifies the length of the sleeves (categorized as short, medium, long, none or unknown).

On the other hand, the Outfit entity is characterized by the attributes "_shirt", "_pants", "_shoe" and "_name". Each of these attributes except "_name" refers to an association that refers to the Clothe entity, meaning that it is a set composed of individual garments categorized as shirt, pants, and shoes. The _name attribute contains the outfit designation used to identify or describe the outfit's style or intended use (such as "Summer Casual" or "Evening Formal"). The arrows indicate relationships, with the Clothe entity being the target of three different arrows emanating from the Outfit entity attributes _shirt, _pants, and _shoe. Therefore, each set is a combination of exactly one of each type of clothing, which points to a one-to-one relationship between the components of the set and the garments.

**Comment by AnthonyMed13** [comment]
We added this to the documentation
