### ISSUE TITLE
[Lecture Topic Task] Information Flows

### ISSUE THREAD

**Issue by HectorSotelo** [uprm-inso4115-2023-2024-s2/semester-project-photofit-a-closet-inventory-app#152]
Task Description:
Dataflow diagrams

Recommended points:
Urgency - 2
Dificulty - 5

**Comment by Cristina-Figueroa** [comment]
Evaluation Criteria and Guidelines - Milestone 3: 

  • The team uses various diagram types to complement their project
    documentation. They use at least 4 of the diagram types below in a
    way that ENHANCES their documentation.
    
1. Information flows: dataflow diagrams
    
Data Flow Diagram Example:

![image](https://github.com/uprm-inso4115-2023-2024-s2/semester-project-photofit-a-closet-inventory-app/assets/70239790/41d69a3c-e124-454e-95c7-6c7c5a0efc91)

Some more examples: 
         https://www.intellspot.com/data-flow-diagram-examples/

**Comment by Cristina-Figueroa** [comment]
Added two Data Flow Diagrams into document, Level 0 Context Diagram and Level 1 Data Flow Diagram, detailing the three main processes of the app: Managing Closet (add/delete items), Generate Randomized Outfit of the Day, and Managing Outfits (add/delete outfits). I will close the issue as finished.
