### ISSUE TITLE
[Lecture Topic Task] Interaction Scenarios

### ISSUE THREAD

**Issue by HectorSotelo** [uprm-inso4115-2023-2024-s2/semester-project-photofit-a-closet-inventory-app#154]
Task Description:
Event trace diagrams

Recommended points:
Urgency - 2
Dificulty - 5

**Comment by Cristina-Figueroa** [comment]
Evaluation Criteria and Guidelines - Milestone 3: 

  • The team uses various diagram types to complement their project
    documentation. They use at least 4 of the diagram types below in a
    way that ENHANCES their documentation.
    
2. Interaction scenarios: event trace diagrams

    
Event Trace Diagram Example:

![image](https://github.com/uprm-inso4115-2023-2024-s2/semester-project-photofit-a-closet-inventory-app/assets/70239790/426eb33b-acf8-400a-9565-461b7acb6ca4)

![image](https://github.com/uprm-inso4115-2023-2024-s2/semester-project-photofit-a-closet-inventory-app/assets/70239790/e4321124-9900-47ed-abf1-35ab01b5975b)

![image](https://github.com/uprm-inso4115-2023-2024-s2/semester-project-photofit-a-closet-inventory-app/assets/70239790/9f5181c3-5d98-40fe-9bc8-3d674cb167c5)



Some more examples: 
         https://www.youtube.com/watch?v=1d4sSiVoPtY
         https://www.slideserve.com/Jims/sequence-diagrams

**Comment by Cristina-Figueroa** [comment]
Added Event Trace Diagrams for the following Interaction Scenarios: 
1. User takes photo, categorizes it and uploads it to PhotoFit
2. User uses Randomizer feature of the App
3. User Manually Searches for a Pre-Saved Outfit

**Comment by Cristina-Figueroa** [comment]
Already added to document, I will close this issue as finished.
