### ISSUE TITLE
Research Photo-Scanning APIs for Color and Clothing Type Recognition

### ISSUE THREAD

**Issue by Adhel-Esteban1** [uprm-inso4115-2023-2024-s2/semester-project-photofit-a-closet-inventory-app#17]
In this research task, the development team is tasked with exploring and evaluating Photo-Scanning APIs that offer capabilities for recognizing both color and the type of clothes from images. The objective is to identify reliable and efficient APIs that can seamlessly integrate with the PhotoFit app to enhance its functionality. Follow these steps during the research process:

API Identification:
Research and identify reputable Photo-Scanning APIs known for their color recognition and clothing type detection capabilities. Consider popular providers and assess their features, documentation, and community support.

Functionality Evaluation:
Evaluate each API's capabilities in recognizing colors and distinguishing between different types of clothing items (e.g., pants, skirts, shirts, shoes). Check for accuracy, speed, and the range of supported colors and clothing types.

Technical Compatibility:
Assess the technical compatibility of the selected APIs with the technology stack and frameworks chosen for the PhotoFit app. Ensure seamless integration and minimal friction during development.

Pricing and Terms:
Investigate the pricing models and terms of service for each API. Consider factors such as usage limits, pricing tiers, and any potential hidden costs. Aim for a cost-effective and sustainable solution.

Community and Support:
Look into the developer community and support provided by the API providers. Choose APIs with active communities, well-maintained documentation, and responsive support channels.

Security and Privacy:
Prioritize APIs that adhere to security and privacy standards, especially when dealing with user-generated images. Ensure that the chosen APIs align with regulatory requirements and maintain the privacy of user data.

Document the findings, including the pros and cons of each API, and present a comprehensive recommendation based on the evaluation criteria. This research will guide the selection of a suitable Photo-Scanning API for integrating color and clothing type recognition features into the PhotoFit app.

**Comment by misaelmercado1** [comment]
[Research Photo-Scanning APIs for Color and Clothing Type Recognition.pdf](https://github.com/uprm-inso4115-2023-2024-s2/semester-project-photofit-a-closet-inventory-app/files/14353831/Research.Photo-Scanning.APIs.for.Color.and.Clothing.Type.Recognition.pdf)

Made a document reporting on findings with pros and cons and personal reccomendation.
