### ISSUE TITLE
Sketch/Brainstorm local storage functionality

### ISSUE THREAD

**Issue by Adhel-Esteban1** [uprm-inso4115-2023-2024-s2/semester-project-photofit-a-closet-inventory-app#22]
In this collaborative task, the development team is assigned to sketch and brainstorm the implementation of local storage functionality for the PhotoFit app. The goal is to design a robust system that enables the app to store and retrieve user data, ensuring a seamless and efficient experience even when offline.

This collaborative sketching and brainstorming session will lay the foundation for a robust and user-friendly local storage functionality, enhancing the overall reliability and accessibility of the PhotoFit app.

**Comment by misaelmercado1** [comment]
https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/PropertyLists/Introduction/Introduction.html
https://www.answertopia.com/ios/an-example-sqlite-based-ios-app-using-swift-and-fmdb-2/
https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/PropertyLists/Introduction/Introduction.html
https://medium.com/@mukthaharshaik/choose-the-right-local-storage-for-your-use-case-in-react-native-582239312dfd#:~:text=Async%20Storage%20is%20the%20official,in%20separate%20files%20on%20iOS.

[Sketch and Brainstorm Local Functionality.pdf](https://github.com/uprm-inso4115-2023-2024-s2/semester-project-photofit-a-closet-inventory-app/files/14377455/Sketch.and.Brainstorm.Local.Functionality.pdf)

Some useful links found to help with implementation and local storage functionality sketch resumed in pdf file
