### ISSUE TITLE
Add synopsis to the documentation

### ISSUE THREAD

**Issue by AnthonyMed13** [uprm-inso4115-2023-2024-s2/semester-project-photofit-a-closet-inventory-app#29]
For this task one needs to add the synopsis to the documentation of the project.

Here are the guidelines for the synopsis based on the criteria for milestone 1:

 • In the synopsis you can talk about how you'll conduct the project.
  • The synopsis can and should also refer to the domain description,
    the requirements prescription, the software architecture, … Remember
    the synopsis is a concise overview about the project you have
    planned.
  • One way to think about the synopsis is as an executive summary or
    abstract. If you knew that a superior would read only half a page
    and would have to get a full overview of all that your project will
    involve then what would you write? But also keep in mind that this
    has to be complete in so far as everything that your project needs
    to do also needs to be introduced here. You do not want to get into
    a situation where you are doing, say, requirements engineering, but
    you did not mention that in your abstract. Now the superior might
    ask: why is this been worked on? This was not agreed upon.

Tentative Points:

Urgency: 4
Difficulty: 3

**Comment by Cristina-Figueroa** [comment]
I'll work on this issue

**Comment by Cristina-Figueroa** [comment]
This task is done, and has been added to documentation. Issue can be closed
