### ISSUE TITLE
Add derived goals to the documentation

### ISSUE THREAD

**Issue by AnthonyMed13** [uprm-inso4115-2023-2024-s2/semester-project-photofit-a-closet-inventory-app#31]
For this task one needs to add the derived goals to the documentation of the project.

Here are the guidelines for the derived goals following the criteria for milestone 1:

  Your primary goal is described by earlier sections like the current
  situation, the needs you identify, etc. Aside from your primary goal
  your project likely has some secondary goals.

  • Your primary project goal is described by the other sections:
    current situation, needs, ideas, … Here you talk about secondary
    desirable outcomes. These should be substantially different from
    your primary goals and not just reiterations of those primary
    goals. For example, a project concerned with beach quality
    monitoring might have as its primary goal to give information about
    the cleanliness of the water and the beach to beach-goers. A
    secondary goal could be to increase tourism to some lesser known
    beaches or to raise awareness among the public about the need to
    keep the beaches clean.

Tentative Points:

Urgency: 5
Difficulty: 2

**Comment by Cristina-Figueroa** [comment]
I'd like to work on this issue as well

**Comment by Cristina-Figueroa** [comment]
Derived Goals:

- Financial Savings, users may avoid redundant purchases and make informed decisions about their wardrobe, leading to significant long-term financial savings. 

- Environmental Impact, by minimizing clothing waste and contributing to sustainable fashion practices, users will be playing a part in reducing their  environmental impact.  

- Educational Opportunities, users can learn about sustainable fashion practices, wardrobe organization tips, among other things, which creates awareness and empowers users with valuable knowledge  

- Community Engagement, users can connect with like-minded individuals and foster a sense of community in the platform.

**Comment by Cristina-Figueroa** [comment]
Already added to the documentation
