### ISSUE TITLE
[Lecture Topic Task] Create Personas

### ISSUE THREAD

**Issue by Adhel-Esteban1** [uprm-inso4115-2023-2024-s2/semester-project-photofit-a-closet-inventory-app#33]
In this task, the objective is to develop detailed Personas representing key stakeholders involved in the documentation process for the PhotoFit project. These Personas will go beyond demographic details, delving into the roles, responsibilities, goals, and challenges of individuals contributing to the documentation. By crafting nuanced Personas, the documentation team aims to foster a better understanding of the diverse perspectives and needs within the team, ultimately enhancing the effectiveness and relevance of the project's documentation.

Official Evaluation Criteria:
Include personas in your documentation. They allow you to justify
    user stories, features, epics, and requirements in general. A good
    way to start developing your personas is to think about yourself (if
    you are a potential user), friends, family, peers, etc. Anyone you
    might want to make use of your software and benefit from your
    project. Then you identify what all these people have in common and
    you condense their important traits into a few "Frankensteins",
    imaginary people whom you give certain traits that you think are
    plausible for a single person to have. Your main goal here: you
    collection of traits must be easy to remember for everyone around
    the team so that just mentioning the name of the persona immediately
    evokes the traits in everyone's mind.

Urgency 7
Difficulty 4

**Comment by DiegoLIRodriguez** [comment]
Completed in its majority by Diego Rodriguez
