### ISSUE TITLE
Organize articles by color

### ISSUE THREAD

**Issue by Jandel7** [uprm-inso4115-2023-2024-s2/semester-project-photofit-a-closet-inventory-app#43]

**Comment by kevomm** [comment]
In the Closet tab mock data is used to represent clothing items retrieved from a database of some sort. A function is used to randomly generate 100 clothing items (Clothes class) of all types allowed and repeating colors.

Then a horizontal ScrollView is rendered with all items grouped by color. This can later be changed to more adequately represent the desired UI design.
