### ISSUE TITLE
[Lecture Topic Task] Add specific class topics to documentation

### ISSUE THREAD

**Issue by AnthonyMed13** [uprm-inso4115-2023-2024-s2/semester-project-photofit-a-closet-inventory-app#50]
This task requires people to: identify the stakeholder, domain and requirements aquisition, and traceability.

I recommend that this task should be divided bewteen multiple people since it contains different topics.
This should follow the criteria and guidelines for milestone 1.

The following rubrics will have a higher weight than those above:

-------------------------------------------------------------------------------------
  • stakeholder identification
    • initial

      In the initial phase of your project you will already be able to
      identify some stakeholders. Just by thinking about the domain, the
      requirements, actual usage scenarios, growth trajectories, etc.

      • Who are the stakeholders you can identify from the start? Don't
        just name them… elaborate.
      • Why are they stakeholders in your project?
      • How are they related to your project?

    • additional: how, from where,…

      It is likely that you have not found/will not find many of the
      possible stakeholders in your initial consideration. If you assume
      that this is so and that there are stakeholders you have missed:

      How do you plan to find additional stakeholders?  What resources
      could you tap into to find more stakeholders?  When you do find
      additional stakeholders, how are you going to work with them,
      include their views, propagate resulting changes?
-------------------------------------------------------------------------------------
  • domain and requirements acquisition
    • plan

      Here you think about domain and requirements acquisition. How are
      you going to get enough information about the domain and the
      requirements and such information that will allow you to document
      meaningful requirements? Be specific, don't just put some generic
      activities here. For example, just saying that you will consult
      the textbooks of your domain is not enough. On the other hand, if
      your domain is power grid, for example, then one of the things you
      could plan to do is to read and gather information from "Electric
      Power System Basics for the Nonelectrical Professional" 2nd
      Edition by Steven W. Blume.

    • resources

      Which resources will you consider?  Why these resources?  How will
      you incorporate new findings into your existing domain
      understanding?  Does your plan for domain acquisition include
      diverse resources? Stakeholders, literature,…?

-------------------------------------------------------------------------------------
Tentative Points:

Urgency: 8
Difficulty: 7

stakeholder identification should get 10pts
domain and requirements acquisition should get 18pts
traceability should get 28pts

NOTE: This is subject to change

**Comment by diego-velez-upr** [comment]
I will carry out the domain acquisition part.

**Comment by diego-velez-upr** [comment]
@AnthonyMed13 wrote the stakeholder identification and I wrote the domain and requirements acquisition
