### ISSUE TITLE
Archives / Collections Feature

### ISSUE THREAD

**Issue by AngelGonzs** [uprm-inso4115-2023-2024-s2/semester-project-photofit-a-closet-inventory-app#51]
The adition of _Archives_ to the application would benefit users in multiple ways. First off, archives would serve as lists or collections for users to order their clothes in, for example, they could have an Archive of their favorite clothing pieces, another for clothes they want to donate or maybe one for winter clothes.

The other purpose I had initially thought of, was allowing for people that are into Fashion to document their clothing collections into different archives. E.g. a user could make an Archive of all their clothes from a Designer Collection. I think this would appeal to people that consider themselves fashion enthusiasts and is something that other applications don't provide!

**Comment by eternero** [comment]
Added a Draft for the `collection` class on the archives-draft branch.
