### ISSUE TITLE
[Fix Milestone 1 Documentation] Function Signature

### ISSUE THREAD

**Issue by AnthonyMed13** [uprm-inso4115-2023-2024-s2/semester-project-photofit-a-closet-inventory-app#68]
Your function signatures serve the purpose of clarifying actions/operations so they should be together with those actions that they clarify. Without additional text that makes use of these signatures they do not help a reader much in understanding your project. Take, for example, "view closet": why is there a user as a parameter? What do you assume here? For example, you might assume that from a user you can obtain a list of closets and then get a list of all the clothes in all the closets or you could assume that a user has one virtual closet and through the user parameter we can get the clothes in that closet. Another example: "sort closet" only has a category as its parameter, where do the clothes come from? All this shows that without further comment the function signatures are not really telling us enough.

**Comment by misaelmercado1** [comment]
done
