### ISSUE TITLE
[Fix Milestone 1 Documentation] User Stories, Epics, Features

### ISSUE THREAD

**Issue by AnthonyMed13** [uprm-inso4115-2023-2024-s2/semester-project-photofit-a-closet-inventory-app#69]
For the photo capture feature it shouldn't matter whether the picture has already been captured sometime ago or whether I'm capturing a new picture.

"Should" is a bit soft for the acceptance criteria. It's not as bad for the acceptance criteria as it is for actual requirements, but it's much better to state clearly here what you consider acceptable. If you use "should" then it's not clear what you will do when the criterion is not met: would you accept or reject?

How do you plan to manage specific occasions? Say, job interview, wedding, hike through El Yunque, etc.? Do you need some additional features or can this be handled with the tags? You might want to say something about this since I think you talked about special occasions somewhere.

**Comment by sandy-marrero** [comment]
Acceptance criteria wording has been slightly modified to account for the feedback, all three points have been addressed in the documentation.
