### ISSUE TITLE
Design an add clothe screen in Figma

### ISSUE THREAD

**Issue by diego-velez-upr** [uprm-inso4115-2023-2024-s2/semester-project-photofit-a-closet-inventory-app#74]
Currently, in the [PhotoFit UI's Figma](https://www.figma.com/file/ojPtY7fqcm1botgu9QryZf/PhotoFit-UI?type=design&node-id=0%3A1&mode=design&t=0UeX4xXHUhClTn6r-1), there is no mockup for the add clothe screen in the application. This screen should be designed in order to allow developers to properly integrate this into the application.

**Comment by Adhel-Esteban1** [comment]
I can work on this. I'd love this task

**Comment by Adhel-Esteban1** [comment]
I rechecked the Figma, and there's a round + button on the corner of the Closet Page. The page besides it is the screen that would appear after the photo snap. Is there something else in particular we're looking to design?

**Comment by Adhel-Esteban1** [comment]
![Blank diagram - Page 1 (1)](https://github.com/uprm-inso4115-2023-2024-s2/semester-project-photofit-a-closet-inventory-app/assets/93483234/504c07c7-7ba1-4b73-a036-fa90c3515d8f)

Here's the diagram of the UI.

**Comment by Adhel-Esteban1** [comment]
Recommended points: 
Urgency:1
Difficulty: 1
