### ISSUE TITLE
Implement proper edit clothe screen UI

### ISSUE THREAD

**Issue by diego-velez-upr** [uprm-inso4115-2023-2024-s2/semester-project-photofit-a-closet-inventory-app#75]
Currently, the add clothe screen in the application is a placeholder because there are currently no add clothe screen UI mockups. This issue depend on issue #74, since the UI mockups need to be done to carry this out.

**Comment by diego-velez-upr** [comment]
The add clothe screen is the edit clothe screen. It was decided that the application would use the same screen for adding and editing, with the only difference being that when you want to add clothe you take a picture of the clothe then you edit the clothe.

**Comment by Adhel-Esteban1** [comment]
Here's what the UI will consist of:
- The red button to remove the current photo displayed
- The green button to add a photo to the cloth item's gallery. This will call the camera feature implemented by Jafet. 
- The filters section which could still use some updating as necessary. 
- And saving the item to display it.

![Screenshot 2024-03-07 at 3 58 38 PM](https://github.com/uprm-inso4115-2023-2024-s2/semester-project-photofit-a-closet-inventory-app/assets/93483234/0e4f16b2-8919-486e-aa3c-01766a3fa2ed)

**Comment by Adhel-Esteban1** [comment]
This issue has been done 4 days ago. I will close this now. I see no recommended points. How does this sound?

Urgency: 4
Difficulty: 5
