### ISSUE TITLE
Implement the proper main screen

### ISSUE THREAD

**Issue by diego-velez-upr** [uprm-inso4115-2023-2024-s2/semester-project-photofit-a-closet-inventory-app#82]
Currently, the main/home screen of the application does not match the main screen of [PhotoFit UI's Figma](https://www.figma.com/file/ojPtY7fqcm1botgu9QryZf/PhotoFit-UI?type=design&node-id=0%3A1&mode=design&t=0UeX4xXHUhClTn6r-1). This task shall implement the proper UI meant for the main page screen.

**Comment by Cristina-Figueroa** [comment]
Added the progress I made from Outfits page and Edit Page in the document, it is not complete but will close this issue and open a new one for what still needs to be implemented for milestone #3

**Comment by Adhel-Esteban1** [comment]
I'll take care of this. 
Recommended Points:
- Urgency: 3
- Difficulty: 3
-

**Comment by Adhel-Esteban1** [comment]
OK, I implemented the main screen placeholders, all that's left to implement is the logic. That will be a tad more complicated, so I will raise the points so that someone who knows can take 50% of the points.

**Comment by Adhel-Esteban1** [comment]
New recommended points for logic + front end:
Urgency: 5
Difficulty: 7
Since I worked on the front end, I will take 50% of these points. However, I'll try to see if I can implement something should nobody show up.

**Comment by Adhel-Esteban1** [comment]
A correction, this is implementation of the UI alone. That has been handled completely. The difficulty will be much less though. The logic is handled on #118 
Urgency: 3
Difficulty: 2

I will close this issue now.
