### ISSUE TITLE
Implement the proper outfits screen

### ISSUE THREAD

**Issue by diego-velez-upr** [uprm-inso4115-2023-2024-s2/semester-project-photofit-a-closet-inventory-app#84]
Currently, the outfits screen of the application does not match the outfits screen of [PhotoFit UI's Figma](https://www.figma.com/file/ojPtY7fqcm1botgu9QryZf/PhotoFit-UI?type=design&node-id=0%3A1&mode=design&t=0UeX4xXHUhClTn6r-1). This task shall implement the proper UI meant for the outfits screen.

**Comment by Cristina-Figueroa** [comment]
I'm interested in working on this issue

**Comment by Cristina-Figueroa** [comment]
Added the progress made on the Outfits Page and Edit Page in the document, it is not complete but will close this issue and open a new one for what needs to be implemented for milestone#3
