### ISSUE TITLE
[Lecture Topic Task] Document Candidate Resolutions

### ISSUE THREAD

**Issue by Adhel-Esteban1** [uprm-inso4115-2023-2024-s2/semester-project-photofit-a-closet-inventory-app#85]
Task Description:
Document the candidate resolutions generated in response to inconsistencies identified in the project. Provide detailed information on at least three instances where further elicitation techniques were applied to reach candidate resolutions. Additionally, highlight at least three cases where specific resolution tactics were employed to address inconsistencies. Ensure that the documentation provides clarity on the nature of each inconsistency, the applied techniques, and the resulting candidate resolutions.

Evaluation Criteria:

1. The documentation includes a comprehensive list of candidate resolutions generated to address inconsistencies within the project.
2. For at least three instances, the documentation details the elicitation techniques employed to arrive at candidate resolutions.
3. For at least three cases, the documentation outlines the resolution tactics applied to mitigate inconsistencies.
4. Each documented instance provides a clear description of the inconsistency, the applied techniques or tactics, and the resulting candidate resolutions.
5. The documentation effectively communicates the rationale behind selecting particular resolution approaches.

Recommended points:
Urgency - 6
Dificulty - 6

**Comment by Adhel-Esteban1** [comment]
@HectorSotelo @print-Eruki I'd love to work on this one. I don't exactly see it on the project board, so I let you know through here.

**Comment by HectorSotelo** [comment]
Donezo 👍
