### ISSUE TITLE
[Lecture Topic Task] Risk Identification using FMEA

### ISSUE THREAD

**Issue by Adhel-Esteban1** [uprm-inso4115-2023-2024-s2/semester-project-photofit-a-closet-inventory-app#86]
Task Description:
Identify and document risks within the project using both Failure Modes and Effects Analysis (FMEA) and guidewords. Provide at least three instances where FMEA is employed to identify potential risks, and at least three cases where guidewords are used in conjunction with scenarios to generate risks. Ensure that each identified risk is accompanied by a clear description, potential consequences, and proposed mitigation strategies. Use scenarios to illustrate and contextualize the identified risks.

Evaluation Criteria:

1. The documentation includes a minimum of three instances where FMEA is utilized for risk identification.
2. The documentation provides at least three cases where guidewords are employed along with scenarios to generate risks.
3. Each identified risk is accompanied by a detailed description, potential consequences, and proposed mitigation strategies.
4. Scenarios are effectively used to illustrate and contextualize the identified risks, enhancing understanding.
5. The documentation demonstrates a comprehensive approach to risk identification, showcasing the project team's use of both FMEA and guidewords.

Recommended points:
Urgency - 6
Dificulty - 6

**Comment by DiegoLIRodriguez** [comment]
Completed and submitted to documentation
