### ISSUE TITLE
Design search UI elements/screen

### ISSUE THREAD

**Issue by diego-velez-upr** [uprm-inso4115-2023-2024-s2/semester-project-photofit-a-closet-inventory-app#88]
Currently, in the [PhotoFit UI's Figma](https://www.figma.com/file/ojPtY7fqcm1botgu9QryZf/PhotoFit-UI?type=design&node-id=0%3A1&mode=design&t=0UeX4xXHUhClTn6r-1), there are no UI search element or screen design. This UI mockup should be created in order to allow developers to properly integrate searching functionality for the users.

**Comment by JoseLQV** [comment]
Could be useful to add Color palettes recommendation as well in this issue

**Comment by Adhel-Esteban1** [comment]
> Could be useful to add Color palettes recommendation as well in this issue

I suggest keeping those issues apart for easier tracking.

**Comment by sandy-marrero** [comment]
Search UI Screen can be found in the Photofit Figma on the page called **Milestone 2**
