### ISSUE TITLE
[Lecture Topic Task] Add questionnaire for requirements acquisition

### ISSUE THREAD

**Issue by diego-velez-upr** [uprm-inso4115-2023-2024-s2/semester-project-photofit-a-closet-inventory-app#90]
The project reviewed the requirements documentation and ensures that at least one meaningful questionnaire for requirements acquisition is included.

**Comment by Adhel-Esteban1** [comment]
Recommended points: 
Urgency: 3
Difficulty: 3

**Comment by Adhel-Esteban1** [comment]
Do we need to carry forth the questionnaire, or can just plan it out and carry it out for the next milestone?

**Comment by Adhel-Esteban1** [comment]
I will close this issue now to make sure it's on time. I'll add the results of the questionnaire tomorrow.
