### ISSUE TITLE
[Fix Milestone 1 Documentation] Domain and Requirement Acquisition

### ISSUE THREAD

**Issue by HectorSotelo** [uprm-inso4115-2023-2024-s2/semester-project-photofit-a-closet-inventory-app#98]
For your domain and requirement acquisition, even if you have not done any interviews yet, you could already plan them and e.g. provide some interview questions, a selection on who you will specifically approach and when, etc.

Recommended points:
Urgency - #
Dificulty - #

**Comment by Adhel-Esteban1** [comment]
Finished adding the 2.2.6 Domain Requirements Acquisition part on the documentation.
