### ISSUE TITLE
[Fix Milestone 1 Documentation] Traceability

### ISSUE THREAD

**Issue by HectorSotelo** [uprm-inso4115-2023-2024-s2/semester-project-photofit-a-closet-inventory-app#99]
I explained in class the difference between "tracing" and "traceability". What you present here is tracing: you go through the parts of the document and trace the connection between the items. Traceability refers to the fact that the document is written/linked in such a way that it supports tracing.

Recommended points:
Urgency - #
Dificulty - #

**Comment by AnthonyMed13** [comment]
I saw that this issue has been completed I recommend closing it @RicardoJRSs
